# Generated by Django 3.1.7 on 2021-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='summa',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Summa'),
        ),
    ]
