# Generated by Django 3.1.7 on 2021-03-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0002_auto_20210317_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance'),
        ),
    ]
