# Generated by Django 3.1.7 on 2021-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purse', '0003_auto_20210318_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance'),
        ),
    ]
